### ISSUE TITLE
Error Game Crashed

### ISSUE THREAD

**Issue by RaoqTheWiz** [Hephaestus-Dev/TinyTweaks#23]
Not sure what is causing it to crash but here is the Crash Report:

(If you need anymore details please ask but this is all I got).

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 8/19/20 8:06 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gud_fps'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.gudenau.minecraft.fps.GudFPS.tryLoad(GudFPS.java:87)
	at net.gudenau.minecraft.fps.GudFPS.forceLoadJar(GudFPS.java:78)
	at net.gudenau.minecraft.fps.GudFPS.onInitialize(GudFPS.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2281/728928021.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getSoulFireSprite(Lnet/minecraft/class_4730;)Lnet/minecraft/class_1058; in tweaks.mixins.json:client.gui.hud.RenderSoulFire failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tinytweaks-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 781319472 bytes (745 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		allure: Allure 1.2.3
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		autofish: Autofish 0.9.0
		backslot: BackSlot 1.0.0
		beaconsforall: Beacons For All 1.2.0-1.16.2
		bedspreads: Bedspreads 1.1.0-1.16.2
		betterthanmending: BetterThanMending 1.2.0
		blue_endless_jankson: jankson +
		bowinfinityfix: Bow Infinity Fix rv9
		caelus: Caelus API 0.0.8-1.16.2
		camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.3+1.16.2
		cardinal-components-base: Cardinal Components API (base) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-item: Cardinal Components API (items) 2.5.0-nightly.1.16.2-rc2
		carpet: Carpet Mod in Fabric 1.4.8
		carpet-extra: Carpet Extra 1.4.8
		chains: Chains-Link 1.2.0
		cleanview: CleanView 1.16.2-v1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.8
		cloth-config2: Cloth Config v4 4.7.0-unstable
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		combatedit: CombatEdit 1.2.0
		craftingpad: Crafting Pad 1.16.2-fabric0.17.2-1.0.5
		crowmap: Crowmap 1.0.1
		curioofundying: Curio of Undying 1.0.1-1.16.2
		curios: Curios API 0.0.6-1.16.2
		curiouselytra: Curious Elytra 1.0.1-1.16.2
		dontgrow: Dont Grow 1.0.1
		doublejump: Double Jump Mod 1.16.1-1.0.0
		eatanddrink: Eat And Drink 1.1.0
		enchantablehorsearmor: Enchantable Horse Armor *
		enderitemod: Enderite Mod 1.2.0
		expandedconcrete: Expanded Concrete 0.0.2
		fabric: Fabric API 0.18.0+build.397-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b4e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+02fb8fda4e
		fabricforfabric: Fabric for Fabric! 1.2.4
		fabricloader: Fabric Loader 0.9.1+build.205
		flight_rings: Flight Rings 1.2.1
		glassential: Glassential *
		gud_fps: Gud FPS 0.0.2
		harvest: Harvest *
		honeymod: Honey mod 1.0.3
		houraielixir: Hourai Elixir 5
		howlingwolves: Howling Wolves 1.0.0+build.1
		infinitevillagertrading: InfiniteVillagerTrading 1.16.2-fabric0.17.2-1.0.2
		inventorysorter: Inventory Sorter 1.7.2-1.16
		irishwolves: Irish Wolves 1.0.0
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lambdynlights: LambDynamicLights 1.3.0+1.16.2
		lapisreserve: Lapis Reserve 1.0.5
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		magic_mirror: Magic Mirror 1.0.2
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.2
		mo_glass: Mo Glass 1.4-MC1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.0
		moretotems: More Totems 2.6.0
		mtca: More Totems Curios Addon 1.0.1
		netherite_plus: Netherite Plus Mod beta-1.9.1
		netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.2
		nogizmo: No Debug Gizmo 1.2
		notrample: No Trample 0.0.2
		obeyhorses: Obey Horses 1.1
		oldnotchapple: Old Notch Apples 1.0.0
		onsoulfire: On Soul Fire 6
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		overworld_two: Overworld 2 1.0.1
		parry: Parry 1.1
		petowner: Pet Owner 1.16.2-1.4
		photoallergiccreepers: Photoallergic Creepers *
		portaltags: Portal Tags 2.0.0+1.16.2
		prone: prone 0.1.1
		pumice: Pumice 0.0.2
		quickshulker: Quick Shulker 1.1.6-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		rebind-narrator: Rebind Narrator 1.0.0
		repairableanvils: Repairable Anvils 0.0.2
		respawnablepets: Respawnable Pets 6
		roughlyenoughitems: Roughly Enough Items 5.2.3
		roughlyenoughitems-api: REI (API) 5.2.3
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.3
		roughlyenoughitems-runtime: REI (Runtime) 5.2.3
		shulkerboxtooltip: Shulker Box Tootip 2.1.1+1.16.2
		shulkularity: Shulkularity 1.0.0
		simple_backpack: SimpleBackpack 1.0.27
		sizeentityattributes: Size Entity Attributes 3
		soulsoilfarmland: Soul Soil Farmland 0.0.2
		spruceui: SpruceUI 1.6.2
		staffofbuilding: Staff of Building 1.2.2-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		strawdummy: Straw Dummy 1.2.0
		thallium: Thallium 1.7
		the_loved_ones: The Loved Ones 1.0.0+1.16.1
		tinytweaks: TinyTweaks 1.0.12
		trees-do-not-float: Trees Do Not Float 1.12.94
		uncraftable: Uncraftables *
		vanilla-toolsets: Vanilla Toolsets 1.3.0
		vanilladeathchest: VanillaDeathChest 1.16.2-1.11.0.6-fabric
		wishingforsunshine: Wishing for Sunshine 1.16.2-2.0.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
	Launched Version: fabric-loader-0.9.1+build.205-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Haven-King** [comment]
This mod is incompatible with `onsoulfire`, another mod you have installed that also makes soul fire blue on entities. If you uninstall that mod, the crash will go away :)

**Comment by RaoqTheWiz** [comment]
> This mod is incompatible with `onsoulfire`, another mod you have installed that also makes soul fire blue on entities. If you uninstall that mod, the crash will go away :)

Never would have guessed that.. Thought it was Thallium XD. Thanks for the help!
