### ISSUE TITLE
Crashes with Micalibria.

### ISSUE THREAD

**Issue by K0-RR** [Hephaestus-Dev/TinyTweaks#75]
```
[16:09:49] [main/INFO]: Loading for game Minecraft 1.16.5
[16:09:50] [ForkJoinPool-1-worker-5/WARN]: Non-Fabric mod JAR at "/home/k0rr/.local/share/multimc/instances/1.16.5 test/.minecraft/mods/vanguard-uninstaller.jar", ignoring
[16:09:50] [main/INFO]: [FabricLoader] Loading 65 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.11.188, notenoughcrashes@3.2.0, fabricloader@0.11.3, hydrogen@0.2-SNAPSHOT, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, lithium@0.6.4-SNAPSHOT, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, tinytweaks@1.2.3, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, lazydfu@0.1.2, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, starlight@fabric-1.0.0-RC1-59d1f21, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, sodium@0.1.1+build.330, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.5+1.16, micalibria@1.0.2, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, roughlyenoughitems-default-plugin@5.11.188, fabric-screen-handler-api-v1@1.1.5+9354966b7d, modmenu@1.16.8, fabric-command-api-v1@1.1.1+351679a77d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, roughlyenoughitems-runtime@5.11.188, cloth-client-events-v0@1.5.47, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, roughlyenoughitems@5.11.188, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.8.3, autoconfig1u@3.3.1, fabric-resource-loader-v0@0.4.2+ca58154a7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.5+351679a77d, fabric-models-v0@0.2.1+ca58154a7d, climbable@0.2.0, fabric-object-builders-v0@0.7.2+ca58154a7d
[16:09:50] [main/WARN]: Mod `starlight` (fabric-1.0.0-RC1-59d1f21) does not respect SemVer - comparison support is limited.
[16:09:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/k0rr/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[16:09:50] [main/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[16:09:50] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[16:09:50] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[16:09:50] [main/WARN]: Trying to reflect-hack into the class-loader so we can define our own classes in an unrestricted loader...
[16:09:50] [main/WARN]: ** The JVM might warn you with something nasty! **
[16:09:50] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/home/k0rr/.local/share/multimc/instances/1.16.5%20test/.minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[16:09:50] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/home/k0rr/.local/share/multimc/instances/1.16.5%20test/.minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[16:09:50] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/home/k0rr/.local/share/multimc/instances/1.16.5%20test/.minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenEntrySet.class)
[16:09:50] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/home/k0rr/.local/share/multimc/instances/1.16.5%20test/.minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[16:09:51] [main/WARN]: @Redirect conflict. Skipping tweaks.mixins.json:entity.betterlilypads.SprintingParticles->@Redirect::lilyPadsOnWater(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; with priority 1000, already redirected by micalibria.mixins.json:entity.EntityMixin->@Redirect::spawnSprintingParticlesHook(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; with priority 1000
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_2246.<clinit>(class_2246.java:99)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector lilyPadsOnWater(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; in tweaks.mixins.json:entity.betterlilypads.SprintingParticles failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tinytweaks-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 31 more
Process exited with code 255.

```

**Comment by K0-RR** [comment]
https://github.com/Micalobia/Micalibria/issues/4

**Comment by K0-RR** [comment]
https://github.com/Haven-King/TinyTweaks/issues/62#issuecomment-801524411
